services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        platform: linux/x86_64
        ports:
            - '4000:4000'
        volumes:
            - .:/app
        env_file:
            - .env
